<tr style="<?= $this->css; ?>">
    <td align="center" style="color:#aaa;font-size:14px;">
        <?= $this->item['ah_id']; ?>
    </td>
    <td>
        <img src="<?= $this->icon; ?>" style="margin:-3px -3px -5px -3px;" />
    </td>
    <td>
        <?= $this->name; ?>
    </td>
    <td align="center" class="generic-table-symbol" style="color:#aaa;">
        <?= $this->stack; ?>
    </td>
    <td align="right">
        <?= $this->listingPrice; ?>
    </td>
    <td>
        <?= $this->listingTime; ?>
    </td>
    <td align="right">
        <?= $this->soldPrice; ?>
    </td>
    <td>
        <?= $this->soldTime; ?>
    </td>
    <td>
        <?= $this->profit; ?>
    </td>
    <td>
        <?= $this->item['character_name']; ?>
    </td>
    <td align="center" class="form" style="padding:0px;">
        <?= implode("", $this->actions); ?>
    </td>
</tr>
