<style>
    .edit-label { color: #888; font-size: 11px; display: block; margin: 0 0 8px 0; }
</style>
<div class="page">
    <h3><span style="color:#888;">Character &raquo;</span> (<?= $this->character->getID() ;?>) <?= $this->character->getName() ;?></h3>

    <h5>Account</h5>
    <table class="generic-table" border="0" cellpadding="10" cellspacing="0">
        <tr>
            <td><span class="edit-label">ID</span> <?= $this->account->getID() ;?></td>
            <td><span class="edit-label">Name</span> <?= $this->account->getName() ;?></td>
            <td><span class="edit-label">Email #1</span> <?= $this->account->getEmail1() ;?></td>
            <td><span class="edit-label">Email #2</span> <?= $this->account->getEmail2() ;?></td>
            <td><span class="edit-label">Created</span> <?= $this->account->getCreated() ;?></td>
            <td><span class="edit-label">Modified</span> <?= $this->account->getModified() ;?></td>
            <td><span class="edit-label">Status</span> <?= $this->account->getStatus() ;?></td>
            <td><span class="edit-label">Privileges</span> <?= $this->account->getPrivileges() ;?></td>
        </tr>
    </table>

    <h5>Character</h5>
    <table class="generic-table" border="0" cellpadding="10" cellspacing="0">
        <tr>
            <td><span class="edit-label">ID</span> <?= $this->character->getID() ;?></td>
            <td><span class="edit-label">Name</span> <?= $this->character->getName() ;?></td>
            <td><span class="edit-label">Gil</span> <?= $this->gil ;?></td>
            <td><span class="edit-label">Rotation</span> <?= $this->character->getRotation() ;?></td>
            <td><span class="edit-label">Position</span> <?= json_encode($this->character->getPosition()) ;?></td>
            <td><span class="edit-label">Boundary</span> <?= $this->character->getBoundary() ;?></td>
            <td><span class="edit-label">Playtime</span> <?= $this->character->getPlaytime() ;?></td>
            <td><span class="edit-label">GMLevel</span> <?= $this->character->getGMLevel() ;?></td>
        </tr>
    </table>
</div>
