<div class="page">
    <h2>Search</h2>
    <div class="form">
        <table cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td style="padding:0 10px 0 0;">
                    <input type="searchquery" id="searchquery" style="width:100%;" placeholder="<?= $this->searchPlaceHolder; ?>">
                </td>
                <td width="2%">
                    <input type="button" value="Search" />
                </td>
            </tr>
        </table>
    </div>
    <div style="height:30px;"></div>
    <div id="searchresults">
        <?= $this->searchDesc; ?>
    </div>
</div>