<tr>
    <?php foreach ($this->fields as $field) : ?>
        <td width="<?= $field['width']; ?>"><?= $field['value']; ?></td>
    <?php endforeach; ?>

    <?php if ($this->buttons) : ?>
        <td width="50px" align="right">
            <img src="assets/images/edit26.png"
                 class="search-option"
                 title="edit this entry"
                 data-edit="<?= $this->buttonData; ?>" />
        </td>
    <?php else: ?>
        <td width="50px" align="right" style="color:#bbb;">n/a</td>
    <?php endif; ?>
</tr>