<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>
            <?= $this->siteName; ?>
        </title>
        <script>
            window.siteName = '<?= $this->siteName; ?>'
        </script>
        <script type="module" src="assets/js/dist/main.bundle.js"></script>
    </head>
    <body>
        <div id="app">

        </div>
    </body>
</html>
