<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>
            <?= $this->siteName; ?>
        </title>
        <?php $this->siteObj->head(); ?>
    </head>
    <body>
        <header>
            <?php $this->siteObj->get('header'); ?>
        </header>

        <!-- TESTING -->
        <div style="margin:20px 0;">
            <input type="button" value="Load character" onclick="test.editCharacter()" />
        </div>
        <!-- TESTING -->

        <div class="container">
            <nav>
                <?php $this->siteObj->get('nav'); ?>
            </nav>
            <section id="ajax"></section>
        </div>
        <footer>
            <?php $this->siteObj->get('footer'); ?>
        </footer>
    </body>
</html>
