<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>
            <?= $this->siteName; ?>
        </title>
        <script>
            <?= "window.siteName = '{$this->siteName}'"; ?>
        </script>
        <?php
        foreach ($this->assets as $asset) {
            echo $asset;
        }
        ?>
    </head>
    <body>
        <div id="app">

        </div>
    </body>
</html>
